#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#compositor
picom --config ~/.config/picom/picom.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3 #defecto 2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Chromium desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox:Toolkit sticky=on state=floating


#Color borde de ventana
bspc config focused_border_color "#575fcf"
bspc config normal_border_color "#808e9b"

#Restaurar fondo de pantalla con nitrogen
nitrogen --restore &

#configuración de polybar themes
#~/.config/polybar/config 
#bash ~/.config/polybar/launch.sh --forest
$HOME/.config/polybar/launch.sh
wmname LG3D

